AWSTemplateFormatVersion: '2010-09-09'
Description: Example stack to try the Blast Radius visualizer.
Parameters:
  EnvName:
    Type: String
    Default: dev
Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      Tags:
        - Key: Name
          Value: !Sub "${EnvName}-vpc"

  InternetGateway:
    Type: AWS::EC2::InternetGateway

  GatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.1.0/24

  WebSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: web sg
      VpcId: !GetAtt VPC.VpcId

  WebServer:
    Type: AWS::EC2::Instance
    DependsOn: GatewayAttachment
    Properties:
      SubnetId: !Ref PublicSubnet
      SecurityGroupIds:
        - !Ref WebSecurityGroup
      UserData: !Sub "echo deployed into ${VPC} for ${EnvName}"
